services:
  postgres:
    image: postgres:17.2-alpine3.21
    container_name: ${POSTGRES_HOST}
    restart: always
    env_file:
      - .env
      - .env.local
    networks:
      - postgres_net
      - backend_net
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./database/postgres:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin", "-d", "groupe11"]
      interval: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    env_file:
      - .env
      - .env.local
    ports:
      - "${PGADMIN_PORT}:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./database/pgadmin/servers.json:/pgadmin4/servers.json
    networks:
      postgres_net:
    depends_on:
      - postgres
      
networks:
  postgres_net:
    driver: bridge
  backend_net:
    external: true

volumes:
  postgres_data:
  pgadmin_data: