services:
  readme:
    image: alpine:latest 
    container_name: readme
    volumes:
      - ./instruction.txt:/instruction.txt
    command: cat ./instruction.txt

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
      args:
        VITE_PORT: ${VITE_PORT}
        ENV_MODE: ${ENV_MODE}
    restart: always
    ports:
      - ${VITE_PORT}:5173
    env_file:
      - .env
      - .env.local
    volumes:
      - ./frontend:/var/www
      - /var/www/node_modules

  backend:
    image: ghcr.io/j-renevier/$(BACKEND_PACKAGE_NAME):v$(BACKEND_PACKAGE_VERSION)
    container_name: backend
    ports:
      - "${FLASK_EXTERNAL_PORT}:${FLASK_INTERNAL_PORT}"
    env_file:
      - .env
      - .env.local
    volumes:
      - ./backend:/app
    networks:
      - backend_net
    depends_on:
      - postgres

  reverse_proxy:
    image: ghcr.io/j-renevier/$(REVERSE_PROXY_PACKAGE_NAME):v$(REVERSE_PROXY_PACKAGE_VERSION)
    container_name: reverse_proxy
    ports:
      - "${NGINX_HTTP_PORT}:80"
      - "${NGINX_HTTPS_PORT}:443"
    env_file:
      - .env
      - .env.local
    networks:
      - backend_net
    depends_on:
      - backend

  postgres:
    image: postgres:17.2-alpine3.21
    container_name: ${POSTGRES_HOST}
    restart: always
    env_file:
      - .env
      - .env.local
    networks:
      - postgres_net
      - backend_net
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./database/postgres:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
      - ./database/backup:/backup
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin", "-d", "groupe11"]
      interval: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    env_file:
      - .env
      - .env.local
    ports:
      - "${PGADMIN_PORT}:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./database/pgadmin/servers.json:/pgadmin4/servers.json
      - ./database/backup:/var/lib/pgadmin/storage  
    networks:
      postgres_net:
    depends_on:
      - postgres

  ollama:
    image: ghcr.io/j-renevier/$(LLM_PACKAGE_NAME):v$(LLM_PACKAGE_VERSION)
    container_name: ollama
    ports:
      - "${OLLAMA_PORT:-11434}:11434"
    volumes:
      - ./llm/ollama:/root/.ollama
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    networks:
      - ollama_net
      - backend_net

networks:
  postgres_net:
    driver: bridge
  backend_net:
    driver: bridge
  ollama_net:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
