###
POST {{protocol}}://{{host}}:{{port}}/api/option
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "name": "Rental"
}

###
GET {{protocol}}://{{host}}:{{port}}/api/option
Authorization: Bearer {{access_token}}
Content-Type: application/json

###
GET {{protocol}}://{{host}}:{{port}}/api/option/1
Authorization: Bearer {{access_token}}
Content-Type: application/json


###
DELETE {{protocol}}://{{host}}:{{port}}/api/option/5
Authorization: Bearer {{access_token}}
Content-Type: application/json

###
PATCH {{protocol}}://{{host}}:{{port}}/api/option/5
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "name" : "test"
}

