###
# @name login
POST {{protocol}}://{{host}}:{{port}}/api/authentication/login
Content-Type: application/json

{
  "identification" : "user39@example.com",
  "password": "ChangeMe45/*"
}

###
@access_token = {{login.response.body.content.access_token}}
@refresh_token = {{login.response.body.content.refresh_token}}

###
GET {{protocol}}://{{host}}:{{port}}/api/tools/version

###
GET {{protocol}}://{{host}}:{{port}}/api/tools/identity/client
Authorization: Bearer {{access_token}}
Content-Type: application/json

###
GET {{protocol}}://{{host}}:{{port}}/api/tools/identity/admin
Authorization: Bearer {{access_token}}
Content-Type: application/json

###
GET {{protocol}}://{{host}}:{{port}}/api/tools/identity/all
Authorization: Bearer {{access_token}}
Content-Type: application/json