###
GET http://localhost:3000/api/users/1
Content-Type: application/json

# {
#   "identification" : "user1@example.com",
#   "password": "ChangeMe"
# }

###
POST {{protocol}}://{{host}}:{{port}}/api/users
Content-Type: application/json

{
  "email" : "user39@example.com",
  "password": "ChangeMe45/*",
  "first_name" : "annie",
  "last_name" : "cordi"
}